In [1]:
from data_transformation import create_basetable
from data_transformation import get_all_train_data
from data_transformation import impute_holiday
import numpy as np

from model import get_input_data
from feature_engineering import *
import pandas as pd

In [2]:
data_raw = get_all_train_data()
data_raw

/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3263: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

,Date,Store,DayOfWeek,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,2013-01-01,1115.0,2.0,0.0,0.0,0.0,0.0,a,1.0,d,c,5350.0,NaN,NaN,1.0,22.0,2012.0,"Mar,Jun,Sept,Dec"
1,2013-01-02,1115.0,3.0,3697.0,305.0,1.0,0.0,0,1.0,d,c,5350.0,NaN,NaN,1.0,22.0,2012.0,"Mar,Jun,Sept,Dec"
2,2013-01-03,1115.0,4.0,4297.0,300.0,1.0,0.0,0,1.0,d,c,5350.0,NaN,NaN,1.0,22.0,2012.0,"Mar,Jun,Sept,Dec"
3,2013-01-04,1115.0,5.0,4540.0,326.0,1.0,0.0,0,1.0,d,c,5350.0,NaN,NaN,1.0,22.0,2012.0,"Mar,Jun,Sept,Dec"
4,2013-01-05,1115.0,6.0,4771.0,339.0,1.0,0.0,0,1.0,d,c,5350.0,NaN,NaN,1.0,22.0,2012.0,"Mar,Jun,Sept,Dec"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637769,2014-06-26,127.0,4.0,3335.0,480.0,1.0,0.0,0,0.0,d,a,1350.0,12.0,2005.0,1.0,13.0,2010.0,"Jan,Apr,Jul,Oct"
637770,2014-06-27,127.0,5.0,4724.0,591.0,1.0,0.0,0,0.0,d,a,1350.0,12.0,2005.0,1.0,13.0,2010.0,"Jan,Apr,Jul,Oct"
637771,2014-06-28,127.0,6.0,5398.0,716.0,1.0,0.0,0,0.0,d,a,1350.0,12.0,2005.0,1.0,13.0,2010.0,"Jan,Apr,Jul,Oct"
637772,2014-06-29,127.0,7.0,0.0,0.0,0.0,0.0,0,0.0,d,a,1350.0,12.0,2005.0,1.0,13.0,2010.0,"Jan,Apr,Jul,Oct"
637773,2014-06-30,127.0,1.0,12410.0,1119.0,1.0,1.0,NaN,0.0,d,a,1350.0,12.0,2005.0,1.0,13.0,2010.0,"Jan,Apr,Jul,Oct"

In [3]:
data_imputed = create_basetable(data_raw,
                                {
                                    'Store': 0,
                                    'StoreType': 'unknown',
                                    'SchoolHoliday': 'unknown',
                                    'Assortment': 'unknown',
                                    'StateHoliday': 'unknown',
                                    'DayOfWeek': 'unknown',
                                    'Promo': 'unknown',
                                    'Promo2': 'unknown',
                                    'CompetitionDistance': -1
                                }
                               )
data_imputed

/home/tom/Desktop/dsr/dsr-minicomp/data_transformation.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_dow[dow_col] = missing_dow[date_col].dt.dayofweek
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/pandas/core/generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
  0%|          | 0/1115 [00:00<?, ?it/s]/home/tom/Desktop/dsr/dsr-minicomp/data_transformation.py:210: RuntimeWarning: Mean of empty slice
  fill_vals = np.nanmean(pd.concat([tmp.shift(7), tmp.shift(14), tmp.shift(21), tmp.shift(28)], axis=1), axis=1)
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1113: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1115/1115 [00:16<00:00, 66.67it/s]
/home/tom/Desktop/dsr/dsr-minicomp/data_transformation.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_open[open_col] = 1.0
/home/tom/Desktop/dsr/dsr-minicomp/data_transformation.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_closed[open_col] = 0.0
/home/tom/Desktop/dsr/dsr-minicomp/data_transformation.py:179: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].replace(0.0, 0)
/home/tom/Desktop/dsr/dsr-minicomp/data_transformation.py:181: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].astype(str)
/home/tom/Desktop/dsr/dsr-minicomp/data_transformation.py:158: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna(default_value)

,Date,Store,DayOfWeek,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
1,2013-01-02,1115.0,3.0,3697.0,305.0,1.0,0,0,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
2,2013-01-03,1115.0,4.0,4297.0,300.0,1.0,0,0,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
3,2013-01-04,1115.0,5.0,4540.0,326.0,1.0,0,0,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
4,2013-01-05,1115.0,6.0,4771.0,339.0,1.0,0,0,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
6,2013-01-07,1115.0,1.0,6905.0,471.0,1.0,1,0,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637768,2014-06-25,127.0,3.0,3575.0,562.0,1.0,0,0,0,d,a,1350.0,12.0,2005.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
637769,2014-06-26,127.0,4.0,3335.0,480.0,1.0,0,0,0,d,a,1350.0,12.0,2005.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
637770,2014-06-27,127.0,5.0,4724.0,591.0,1.0,0,0,0,d,a,1350.0,12.0,2005.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
637771,2014-06-28,127.0,6.0,5398.0,716.0,1.0,0,0,0,d,a,1350.0,12.0,2005.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
637773,2014-06-30,127.0,1.0,12410.0,1119.0,1.0,1,0,0,d,a,1350.0,12.0,2005.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"

In [4]:
#TRAIN VALIDATE SPLIT

In [5]:
def one_hot_encoder_fit_transform(df, col_name):
    
    enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
    
    enc.fit(df[col_name].values.reshape(-1, 1))
    
    return one_hot_encoder_transform(df, col_name, enc), enc

def one_hot_encoder_transform(df, col_name, enc):
    
    encoded_column = pd.DataFrame(enc.transform(df[col_name].values.reshape(-1, 1)),
                                  columns=[col_name + '_' + str(item) for item in range(len(enc.categories_[0]))],
                                  index=df.index
                                  
                                 )
    return pd.concat([df, encoded_column], axis=1).drop(col_name, axis=1)

def target_encoder(df, x_col, y_col):
    
    agg = df.groupby(x_col)[y_col].agg(np.mean).to_dict()
    
    return df[x_col].apply(lambda x: agg[x]).values

In [6]:
col_to_log_transform = ['Customers', 'CompetitionDistance', 'CompetitionSince', 'Promo2SinceNWeeks']
col_to_str = ['Promo', 'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment', 'Promo2']

target_var = 'Sales'

train_vars = [
    'DayOfWeek',
    #'Customers',
    'Promo',
    'StateHoliday',
    'SchoolHoliday',
    'StoreType',
    'Assortment',
    #'CompetitionDistance',
    'Promo2',
    #'CompetitionSince',
    'Competition_missing',
    #'Promo2SinceNWeeks',
    'Promo2SinceNWeeks_missing',
    'PromoStarted',
    'Store',
    #'Week',
    'sin_week',
    'cos_week',
    #'Month',
    'sin_month',
    'cos_month',
    'Customers_log', 
    'CompetitionDistance_log', 
    'CompetitionSince_log', 
    'Promo2SinceNWeeks_log'
]

enc_var_list = [
    'DayOfWeek',
    'Promo',
    'StateHoliday',
    'SchoolHoliday',
    'StoreType',
    'Assortment',##consider labeling
    'Promo2'
]

def custom_transformer(df):

    # creating new features
    generate_CompetitionSince(df)
    
    generate_Promo2SinceNWeeks(df)
    
    generate_PromoStarted(df)
    
    df['Month'] = df['Date'].dt.month
    df['Week'] = df['Date'].dt.week

    # log transform    
    for col in col_to_log_transform:
        df[col + '_log'] = log_transform(df[col])

    #sin-cos transform
    sin_month, cos_month = generate_cyclic_feature_month(df)
    df['sin_month'] = sin_month
    df['cos_month'] = cos_month
    
    sin_week, cos_week = generate_cyclic_feature_week(df)
    df['sin_week'] = sin_week
    df['cos_week'] = cos_week

    # replace and change of types
    df['Promo'] = df['Promo'].replace({0.0: 'n', 0: 'n', 1.0: 'y', 1: 'y'}).astype(str)
    df['Promo2'] = df['Promo2'].replace({0.0: 'n', 0: 'n', 1.0: 'y', 1: 'y'}).astype(str)
    df['SchoolHoliday'] = df['SchoolHoliday'].replace({0.0: 'n', 0: 'n', 1.0: 'y', 1: 'y'}).astype(str)
    df['StateHoliday'] = df['StateHoliday'].replace({'0': 'n'}).astype(str)

    for col in col_to_str:
        df[col] = df[col].astype(str)

In [7]:
def metric(preds, actuals):
    preds = preds.reshape(-1)
    actuals = actuals.reshape(-1)
    assert preds.shape == actuals.shape
    return 100 * np.linalg.norm((actuals - preds) / actuals) / np.sqrt(preds.shape[0])

def rmpse(actuals, preds):
    preds = np.array(preds)
    actuals = np.array(actuals)
    preds = preds.reshape(-1)
    actuals = actuals.reshape(-1)
    assert preds.shape == actuals.shape
    return 100 * np.linalg.norm((actuals - preds) / actuals) / np.sqrt(preds.shape[0])

In [8]:
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestRegressor
import math
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import make_scorer

import pickle


df_base = data_imputed.copy()

kf = KFold(n_splits = 5, shuffle=True, random_state=42)

for i, (train_index, test_index) in enumerate(kf.split(data_imputed)):
    
    if i < 4:
        continue
    
    X_train = df_base.iloc[train_index]
    y_train = df_base.iloc[train_index][target_var]
    
    X_test = df_base.iloc[test_index]
    y_test = df_base.iloc[test_index][target_var]
    
    # Transform
    custom_transformer(X_train)
    custom_transformer(X_test)

    # target encoding
    new_col, target_encoder = target_encode_Stores(X_train)
    X_train['Store'] = new_col
    
    new_col, _ = target_encode_Stores(X_test, target_encoder)
    X_test['Store'] = new_col
    
    # Keep selected features
    X_train = X_train[train_vars]
    X_test = X_test[train_vars]
    
    # OneHotEncoding
    for col in enc_var_list:
        X_train, one_hot_encoder = one_hot_encoder_fit_transform(X_train, col)
        X_test = one_hot_encoder_transform(X_test, col, one_hot_encoder)
    
    # Training
    rfc = RandomForestRegressor(n_jobs=-1, random_state=42)
    
    param_grid = {'max_features': ['auto'], #['auto', math.floor(math.sqrt(X_train.shape[1]))]
                  'n_estimators': [300], #[50, 100, 200, 500]
                  'max_depth': [75] #[20, 50, 75, 100]
                 }
    
    rmpse_scorer = make_scorer(rmpse, greater_is_better=False)

    grid2 = GridSearchCV(estimator=rfc, param_grid=param_grid, scoring=rmpse_scorer)
    grid2.fit(X_train, y_train)
    
    y_pred = grid2.best_estimator_.predict(X_test)
    print(metric(y_pred, np.array(y_test)))
    
    pkl_filename = "./models/model_tom_rf_rmpse.pkl"
    with open(pkl_filename, 'wb') as file:
        pickle.dump(grid2.best_estimator_, file)

/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/pandas/core/generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
/home/tom/Desktop/dsr/dsr-minicomp/feature_engineering.py:130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_data[new_col_name] = promo_started
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Fit TargetEncoder...

/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/tom/anaconda3/envs/dsr/lib/python3.6/site-packages/ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Transform using existing TargetEncoder...
9.779197777501851

In [9]:
grid2.best_estimator_

RandomForestRegressor(max_depth=75, n_estimators=300, n_jobs=-1,
                      random_state=42)

In [10]:
X_train

,Competition_missing,Promo2SinceNWeeks_missing,PromoStarted,Store,sin_week,cos_week,sin_month,cos_month,Customers_log,CompetitionDistance_log,...,StoreType_2,StoreType_3,StoreType_4,Assortment_0,Assortment_1,Assortment_2,Assortment_3,Promo2_0,Promo2_1,Promo2_2
1,True,False,0.0,5813.207977,1.205367e-01,0.992709,5.000000e-01,0.866025,5.598422,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,True,False,0.0,5813.207977,1.205367e-01,0.992709,5.000000e-01,0.866025,5.579730,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,True,False,0.0,5813.207977,1.205367e-01,0.992709,5.000000e-01,0.866025,5.673323,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,True,False,0.0,5813.207977,1.205367e-01,0.992709,5.000000e-01,0.866025,5.717028,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
6,True,False,0.0,5813.207977,2.393157e-01,0.970942,5.000000e-01,0.866025,6.077642,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637768,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.267201,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637769,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.098074,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637770,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.320768,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637771,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.523562,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637773,False,False,0.0,5238.501441,-1.205367e-01,-0.992709,1.224647e-16,-1.000000,6.988413,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
X_test

,Competition_missing,Promo2SinceNWeeks_missing,PromoStarted,Store,sin_week,cos_week,sin_month,cos_month,Customers_log,CompetitionDistance_log,...,StoreType_2,StoreType_3,StoreType_4,Assortment_0,Assortment_1,Assortment_2,Assortment_3,Promo2_0,Promo2_1,Promo2_2
7,True,False,0.0,5813.207977,2.393157e-01,0.970942,5.000000e-01,0.866025,5.780744,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
16,True,False,0.0,5813.207977,3.546049e-01,0.935016,5.000000e-01,0.866025,5.424950,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
18,True,False,0.0,5813.207977,3.546049e-01,0.935016,5.000000e-01,0.866025,5.863631,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
22,True,False,0.0,5813.207977,4.647232e-01,0.885456,5.000000e-01,0.866025,5.765191,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
23,True,False,0.0,5813.207977,4.647232e-01,0.885456,5.000000e-01,0.866025,5.855072,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637739,False,False,0.0,5238.501441,4.647232e-01,-0.885456,5.000000e-01,-0.866025,6.182085,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637755,False,False,0.0,5238.501441,2.393157e-01,-0.970942,1.224647e-16,-1.000000,6.267201,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637757,False,False,0.0,5238.501441,2.393157e-01,-0.970942,1.224647e-16,-1.000000,6.526495,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637764,False,False,0.0,5238.501441,1.205367e-01,-0.992709,1.224647e-16,-1.000000,6.455199,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637767,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.232448,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [12]:
import seaborn as sb

In [13]:
X_train

,Competition_missing,Promo2SinceNWeeks_missing,PromoStarted,Store,sin_week,cos_week,sin_month,cos_month,Customers_log,CompetitionDistance_log,...,StoreType_2,StoreType_3,StoreType_4,Assortment_0,Assortment_1,Assortment_2,Assortment_3,Promo2_0,Promo2_1,Promo2_2
1,True,False,0.0,5813.207977,1.205367e-01,0.992709,5.000000e-01,0.866025,5.598422,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,True,False,0.0,5813.207977,1.205367e-01,0.992709,5.000000e-01,0.866025,5.579730,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,True,False,0.0,5813.207977,1.205367e-01,0.992709,5.000000e-01,0.866025,5.673323,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,True,False,0.0,5813.207977,1.205367e-01,0.992709,5.000000e-01,0.866025,5.717028,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
6,True,False,0.0,5813.207977,2.393157e-01,0.970942,5.000000e-01,0.866025,6.077642,8.585226,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637768,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.267201,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637769,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.098074,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637770,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.320768,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637771,False,False,0.0,5238.501441,1.224647e-16,-1.000000,1.224647e-16,-1.000000,6.523562,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
637773,False,False,0.0,5238.501441,-1.205367e-01,-0.992709,1.224647e-16,-1.000000,6.988413,7.209340,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [15]:
import model

In [16]:
y_pred = score_model_ti()

NameError: name 'score_model_ti' is not defined